### PR TITLE
Minor Bug fix to allow the use of the downloaded Keystone package

### PR DESCRIPTION
**Pull request by Ahmed-Nematallah**

### CODE REVIEW

**Comment by hugsy** [comment]
`pip` package `keystone` is a Web framework, totoally unrelated to Keystone Engine (see https://pypi.python.org/pypi/Keystone).

**Comment by Ahmed-Nematallah** [comment]
Interesting, though, changing it to keystone does work for me... Keystone-engine won't even compile on my system.

That's the only way I can run cemu. 

Neither unicorn, nor capstone compile either but installing them from the installer rather than pip satisfies the dependencies. 

I think the installer instals a package called keystone, not keystone-engine, but pip instals keystone-engine?

**Comment by hugsy** [comment]
I don't know your setup so I can't know how/what works for you. What I am sure of is that `pip install keystone` will install the wrong package, so I cannot accept your change.

**Comment by Ahmed-Nematallah** [comment]
No problem, what about the other commit?

**Comment by hugsy** [comment]
The other commit can be merged, but please send it as another PR as the commits are not linked to each other. This makes tracking easier if anything goes wrong in the future.

**Comment by Ahmed-Nematallah** [comment]
No problem, I'll close this and open another one.

**Pull request closed without merging**
