### PR TITLE
OpenREIL added

### PR DESCRIPTION
**Pull request by drmint80**
REIL library added

### CODE REVIEW

**Comment by hugsy** [comment]
This is epic, gonna test this all very soon !

Thanks for  the PR !

**Comment by drmint80** [comment]
I hope everything has worked :)

**Comment by hugsy** [comment]
Hi mate,

I've just tested this. It is freaking awesome, really a great job.
Do you know if OpenReil can be installed easily on Python3 ?

**Comment by drmint80** [comment]
Thanks mate :) Unfortunately, OpenREIL doesn't support Python3. Currently it supports only Python 2.x.

**Comment by hugsy** [comment]
No worries, I will make some changes so people running `cemu` with Python3 do not even see the conversion button.

Thanks for your PR mate.

**Comment by drmint80** [comment]
Okay bro :) I'll try to add on more innovation.

**Pull request merged**
